"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['radialmenu.py']
DATA_FILES = []
OPTIONS = {
    'iconfile': 'AppIcon.icns',
    'excludes': ['setuptools'] # Prevents setuptools from breaking the build in environments
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
